# Services (or containers) we want to run as part of our application:
services:
  # PHP 8.2 application:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    working_dir: /var/www/html
    # Dependency between services:
    depends_on:
      - mysql
    volumes:
      - './src:/var/www/html'
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_SALT: ${MYSQL_SALT}

  # MySQL 5.7 DB:
  mysql:
    image: mysql:5.7
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: test1

volumes:
  todo-mysql-data:
